name: CI

# NB: add GitHub Actions Secret for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  build:
    name: Heroku-${{ matrix.heroku_stack }} - R${{ matrix.r_version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:

        # use `apt-cache policy r-base-dev` to determine
        # combinations per ubuntu version

        include:

          # heroku-24
          - heroku_stack: "24"
            r_version: "4.4.2"

    env:
      HEROKU_STACK: ${{ matrix.heroku_stack }}
      R_VERSION: ${{ matrix.r_version }}
      BUILDPACK_BRANCH: _next

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build
        run: make --no-builtin-rules build

      - name: Unit Tests
        run: make --no-builtin-rules test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload Artifacts
        run: make --no-builtin-rules upload_artifacts BUILDPACK_VERSION=builds/${GITHUB_RUN_ID}

      - name: Publish
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
        run: make --no-builtin-rules publish BUILDPACK_VERSION=builds/${GITHUB_RUN_ID}
