name: CI

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test - Heroku ${{ matrix.heroku_stack }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        heroku_stack:
        - "22"
        - "20"

    env:
      HEROKU_STACK: ${{ matrix.heroku_stack }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate Build ID
        id: metadata
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          echo "::set-output name=BUILD_ID::${branch}-${sha}"

      - name: Build
        run: make --no-builtin-rules build

      - name: Unit Tests
        run: make --no-builtin-rules test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Artifacts
        run: make --no-builtin-rules upload_artifacts BUILDPACK_VERSION=${{ steps.metadata.outputs.BUILD_ID }}

      - name: Publish
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
        run: make --no-builtin-rules publish BUILDPACK_VERSION=${{ steps.metadata.outputs.BUILD_ID }}
