name: CI

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Heroku-${{ matrix.heroku_stack }} - R${{ matrix.r_version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:

        # use `apt-cache policy r-base-dev` to determine
        # combinations per ubuntu version

        include:

          - heroku_stack: "22"
            r_version: "4.2.1"
          - heroku_stack: "22"
            r_version: "4.1.2"

          - heroku_stack: "20"
            r_version: "4.2.1"
          - heroku_stack: "20"
            r_version: "4.1.3"
          - heroku_stack: "20"
            r_version: "4.0.5"

          - heroku_stack: "18"
            r_version: "4.2.0"
          - heroku_stack: "18"
            r_version: "4.1.3"
          - heroku_stack: "18"
            r_version: "4.0.5"

    env:
      HEROKU_STACK: ${{ matrix.heroku_stack }}
      R_VERSION: ${{ matrix.r_version }}
      BUILDPACK_BRANCH: _next

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build
        run: make --no-builtin-rules build

      - name: Unit Tests
        run: make --no-builtin-rules test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Artifacts
        run: make --no-builtin-rules upload_artifacts BUILDPACK_VERSION=${GITHUB_SHA}

      - name: Publish
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
        run: make --no-builtin-rules publish BUILDPACK_VERSION=${GITHUB_SHA}
