name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build & Test - Heroku ${{matrix.heroku_stack}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        heroku_stack: ['18', '16']
    env:
      BUILDPACK_VERSION: builds/build-${{GITHUB_RUN_NUMBER}}
      HEROKU_STACK: ${{heroku_stack}}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build
        run: make --no-builtin-rules build
      - name: Unit Test
        run: make --no-builtin-rules test
      # - name: Publish Test Artifacts
      #   run: make --no-builtin-rules publish
